import type { Metadata } from "next";
import SessionWrapper from './components/SessionWrapper';
import { ToastContainer } from 'react-toastify';
import "./globals.css";


export const metadata: Metadata = {
  title: {
    default: "Nextjs14 Chat-App",
    template: "%s | Chat"
  },
  description: 'Generated by NextJS14',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (  
    <html lang="en">
      <body>
        <SessionWrapper>
          <ToastContainer />
            {children}
        </SessionWrapper>        
      </body>
    </html>
  );
}
